# Generated by Django 2.2.9 on 2020-01-18 17:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proponente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cnpj', models.CharField(blank=True, default='', max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Digite CNPJ no formato XX.XXX.XXX/XXXX-XX.', regex='(^\\d{2}\\.\\d{3}\\.\\d{3}\\/\\d{4}\\-\\d{2}$)')], verbose_name='CNPJ')),
                ('razao_social', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razão Social')),
                ('end_logradouro', models.CharField(blank=True, max_length=100, verbose_name='endereço')),
                ('end_cidade', models.CharField(blank=True, max_length=80, verbose_name='cidade')),
                ('end_uf', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MG', 'Minas Gerais'), ('MS', 'Mato Grosso do Sul'), ('MT', 'Mato Grosso'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('PR', 'Paraná'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('RS', 'Rio Grande do Sul'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('TO', 'Tocantins')], default='SP', max_length=2, verbose_name='estado')),
                ('end_cep', models.CharField(blank=True, default='', max_length=10, validators=[django.core.validators.RegexValidator(message='Digite o CEP no formato XXXXX-XXX. Com 8 digitos', regex='^\\d{5}-\\d{3}$')], verbose_name='cep')),
                ('telefone', models.CharField(blank=True, default='', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Digite o telefone no formato (XX) 12345-6789. Entre 8 ou 9 digitos', regex='^\\(\\d{2}\\) [\\d\\-]{9,10}$')], verbose_name='Telefone')),
                ('email', models.CharField(blank=True, default='', max_length=255, null=True, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='E-mail')),
                ('responsavel', models.CharField(blank=True, max_length=255, null=True, verbose_name='Responsável')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Proponente',
                'verbose_name_plural': 'Proponentes',
            },
        ),
        migrations.CreateModel(
            name='OfertaDeUniforme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Preço')),
                ('proponente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_de_uniformes', to='proponentes.Proponente')),
                ('uniforme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proponentes', to='core.Uniforme')),
            ],
            options={
                'verbose_name': 'oferta de uniforme',
                'verbose_name_plural': 'ofertas de uniforme',
                'unique_together': {('proponente', 'uniforme')},
            },
        ),
    ]
