# Generated by Django 2.2.9 on 2020-01-17 16:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponentes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proponente',
            name='cnpj',
            field=models.CharField(blank=True, default='', max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Digite CNPJ no formato XX.XXX.XXX/XXXX-XX.', regex='(^\\d{2}\\.\\d{3}\\.\\d{3}\\/\\d{4}\\-\\d{2}$)')], verbose_name='CNPJ'),
        ),
    ]
