# Generated by Django 2.2.9 on 2020-01-21 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proponentes', '0004_proponente_meios_de_recebimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertadeuniforme',
            name='proponente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_de_uniformes', to='proponentes.Proponente'),
        ),
    ]
