# Generated by Django 2.2.9 on 2020-01-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponentes', '0006_listanegra'),
    ]

    operations = [
        migrations.AddField(
            model_name='proponente',
            name='status',
            field=models.CharField(choices=[('INSCRITO', 'Inscrito'), ('BLOQUEADO', 'Bloqueado')], default='INSCRITO', max_length=15, verbose_name='status'),
        ),
    ]
