# Generated by Django 2.2.9 on 2020-01-17 16:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uniforme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(blank=True, default='', max_length=100, unique=True, verbose_name='Peça de uniforme')),
            ],
            options={
                'verbose_name': 'Peça de Uniforme',
                'verbose_name_plural': 'Peças de Uniforme',
            },
        ),
    ]
