# Generated by Django 2.2.9 on 2020-01-18 20:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeioDeRecebimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(blank=True, default='', max_length=100, unique=True, verbose_name='Meio de recebimento')),
            ],
            options={
                'verbose_name': 'Meio de recebimento',
                'verbose_name_plural': 'Meios de recebimento',
            },
        ),
    ]
