# Generated by Django 2.2.9 on 2020-01-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='validado',
            field=models.BooleanField(default=False, help_text='Identificar se o cadastro de usuário já foi validado', verbose_name='Validado'),
        ),
    ]
